version: 2
jobs:
    build:
        docker:
        - image: circleci/python:latest
        steps:
        - checkout
        - store_artifacts:
            path: /code/uptime.x2c0.net
            destination: up
        - run:
            name: Install AWSCLI
            command: sudo pip install awscli
        - deploy:
            name: Deploy to S3 if tests pass and branch is Master
            command: |
             if [ "${CIRCLE_BRANCH}" == "master" ]; then
               aws s3 sync . s3://x2c0-uptime --delete && aws cloudfront create-invalidation --distribution-id E14TJS4MZRS3CU --paths '/*'
             else
               echo "Not master branch so not deploying"
             fi
